server:
  port: 5000

simulado:
  base-url: http://localhost:3001
  timeouts:
    connect-ms: 500
    response-ms: 6000

spring:
  threads:
    virtual:
      enabled: true

  cache:
    cache-names: productDetail
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m


